spring.application.name=TodoList

# データベースのホスト名
spring.datasource.hostname=localhost

# データベースのポート番号
spring.datasource.port=5432

# データベース名
spring.datasource.database=todo_list_db

# データベース接続時に指定するオプション
spring.datasource.option=characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B9&rewriteBatchedStatements=true


# データベースのドライバクラス名
# postgresql以外は動作しません
spring.datasource.driver-class-name=org.postgresql.Driver

# データベースのユーザー名
spring.datasource.username=postgres

# データベースのパスワード
spring.datasource.password=password

